### ISSUE TITLE
Get basework laid down for server

### ISSUE THREAD

**Issue by bienzaaron** [Purdue-ACM-SIGAPP/StudyTables-server#1]
Get users, courses, event objects created.

Preferably using Node + Mongo

edit: don't think I can assign myself

**Comment by vidia** [comment]
Just a comment for everyone else, because I mentioned this to you. Mongo or SQL is fine as long as we have a reason for it. The user's courses and events will probably be pretty basic at first which is fine. Add whatever you think should be there. 

Finally, when making the API routes please use a format similar to this: 

`example.com/api/v1/event`

Basically put the version of the api into the path. This is something we didnt do with Laundry and it made things difficult for us down the line.

**Comment by bienzaaron** [comment]
#2 -- sure things will need to change as we move forward

**Comment by vidia** [comment]
Merged in #2
